- name: looptest
  hosts: all
  tasks:
    # emit a debug message containing the content of each file.
    - debug:
        msg: "{{ item }}"
      with_items:
        - first_example_file
        - second_example_file
