- name: looptest
  hosts: all
  connection: local
  tasks:
    # emit a debug message containing the content of each file.
    - debug:
        msg: "{{ item }}"
      with_items:
        - first
        - second
