- name: run show version
  connection: local
  hosts: all
  tasks:
    - name: run show version
      ios_command:
        commands: 
          - show version
      register: result
    - debug: var=result
